# Generated by Django 4.2.7 on 2023-11-28 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('appellidoP', models.CharField(max_length=50)),
                ('appellidoM', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(auto_now=True)),
                ('tiempo_elaboracion', models.IntegerField(default=0)),
                ('dias_retraso', models.IntegerField(default=0)),
                ('descripcion', models.TextField(max_length=240)),
                ('observaciones', models.TextField(default='')),
                ('id_estatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.estatus')),
                ('id_prioridad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.prioridad')),
                ('id_tema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.tema')),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
    ]
