# Generated by Django 4.2.6 on 2023-11-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreAbr',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.estatus'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.prioridad'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tema'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
        ),
    ]
